name : Create the Docker image and push to Docker Hub
on : 
   push : 
      branches : [main]
jobs :
    build-and-push-docker-image :
        runs-on : ubuntu-latest
        steps :
            - name : Checkout the repo
              uses : actions/checkout@v4
            - name: log into Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name : Build the Docker Image
              run : docker build -t sanjaydev/telegram-bot:latest .
            - name : Push the Docker Image
              run : docker push sanjaydev/telegram-bot:latest

          
  